//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANLGX
    {
        public int ANLGX_ID { get; set; }
        public Nullable<int> NEFT_ID { get; set; }
        public string TTL { get; set; }
    }
}
