//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSAY_ORG_DATA
    {
        public int REC_ID { get; set; }
        public Nullable<int> LIBID { get; set; }
        public string LIBNAME { get; set; }
        public Nullable<int> FOLDERID { get; set; }
        public string FOLDNAME { get; set; }
    }
}
