//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASIC_PROPERTIES_4
    {
        public int CRUDE_ID { get; set; }
        public string CRUDE { get; set; }
        public Nullable<int> CUT_ID { get; set; }
        public string CUT { get; set; }
        public Nullable<double> FRACT { get; set; }
        public Nullable<double> IBP { get; set; }
        public Nullable<double> FBP { get; set; }
        public Nullable<double> SPG { get; set; }
        public Nullable<double> SULF { get; set; }
        public Nullable<double> POUR { get; set; }
        public Nullable<double> ABP { get; set; }
        public Nullable<double> ARO { get; set; }
        public Nullable<double> API { get; set; }
        public Nullable<double> CIX { get; set; }
        public Nullable<double> CST50C { get; set; }
        public Nullable<double> FLS { get; set; }
        public Nullable<double> N2A { get; set; }
        public Nullable<double> CST20C { get; set; }
        public Nullable<double> PAR { get; set; }
        public Nullable<double> XC { get; set; }
        public Nullable<byte> IDC { get; set; }
    }
}
