//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUT_PROP
    {
        public int CUT_ID { get; set; }
        public Nullable<int> PROP_ID { get; set; }
        public Nullable<double> XVALUE { get; set; }
        public Nullable<double> YVALUE { get; set; }
    }
}
