//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUT_PROPERTIES
    {
        public string Фр { get; set; }
        public Nullable<double> Выход__вес { get; set; }
        public Nullable<double> T_нк { get; set; }
        public Nullable<double> T_кк { get; set; }
        public Nullable<double> d_4_20_ { get; set; }
        public Nullable<double> Сера__вес { get; set; }
        public Nullable<double> Парафины___вес { get; set; }
        public Nullable<double> T_застыв { get; set; }
        public Nullable<double> T_начкрист__C { get; set; }
        public Nullable<double> Вязк_100С___сст { get; set; }
        public Nullable<double> ЦЧ { get; set; }
        public Nullable<double> Кокс__вес { get; set; }
        public Nullable<double> ОЧ_иссл { get; set; }
        public Nullable<double> Ванадий_ppm { get; set; }
        public Nullable<double> T_прфплав { get; set; }
        public Nullable<double> ВУ_80 { get; set; }
        public Nullable<double> ВУ_100 { get; set; }
        public int CUT_ID { get; set; }
    }
}
