//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMarkEntities : DbContext
    {
        public dbMarkEntities()
            : base("name=dbMarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALL_CRUDE_DATA> ALL_CRUDE_DATA { get; set; }
        public virtual DbSet<ANLGX> ANLGX { get; set; }
        public virtual DbSet<ASSAY_ORG_DATA> ASSAY_ORG_DATA { get; set; }
        public virtual DbSet<BASIC_PROPERTIES> BASIC_PROPERTIES { get; set; }
        public virtual DbSet<BASIC_PROPERTIES_4> BASIC_PROPERTIES_4 { get; set; }
        public virtual DbSet<Basic_Properties_5> Basic_Properties_5 { get; set; }
        public virtual DbSet<BASIC_PROPERTIES_STARAYA_STRUCTURA> BASIC_PROPERTIES_STARAYA_STRUCTURA { get; set; }
        public virtual DbSet<COPY_PROPERTIES> COPY_PROPERTIES { get; set; }
        public virtual DbSet<CRUDE_ASTM> CRUDE_ASTM { get; set; }
        public virtual DbSet<CRUDE_CHEMVIEW> CRUDE_CHEMVIEW { get; set; }
        public virtual DbSet<CUT_PROP> CUT_PROP { get; set; }
        public virtual DbSet<CUT_PROPERTIES> CUT_PROPERTIES { get; set; }
        public virtual DbSet<CUT_URALS> CUT_URALS { get; set; }
        public virtual DbSet<FF> FF { get; set; }
        public virtual DbSet<GEOREG> GEOREG { get; set; }
        public virtual DbSet<LIBRARY> LIBRARY { get; set; }
        public virtual DbSet<PROP_IMAGEVIEW> PROP_IMAGEVIEW { get; set; }
        public virtual DbSet<PROPERTIES> PROPERTIES { get; set; }
        public virtual DbSet<RPMS_BLEND> RPMS_BLEND { get; set; }
        public virtual DbSet<RPMS_CONV> RPMS_CONV { get; set; }
        public virtual DbSet<RPMS_RAWM> RPMS_RAWM { get; set; }
        public virtual DbSet<RPMS_RECURSE> RPMS_RECURSE { get; set; }
        public virtual DbSet<RPMS_RPMSFN> RPMS_RPMSFN { get; set; }
        public virtual DbSet<RPMS_SALES> RPMS_SALES { get; set; }
        public virtual DbSet<RPMS_SPEC> RPMS_SPEC { get; set; }
        public virtual DbSet<RPMS_SPECTEXT> RPMS_SPECTEXT { get; set; }
        public virtual DbSet<RPMS_UBAL> RPMS_UBAL { get; set; }
        public virtual DbSet<RPMS_YY1> RPMS_YY1 { get; set; }
        public virtual DbSet<SULF_VS_AVBP> SULF_VS_AVBP { get; set; }
        public virtual DbSet<URALS> URALS { get; set; }
        public virtual DbSet<VALUEPARAM> VALUEPARAM { get; set; }
        public virtual DbSet<VNIINP_PROPERTIES> VNIINP_PROPERTIES { get; set; }
        public virtual DbSet<VNIINP_PROPERTIES2> VNIINP_PROPERTIES2 { get; set; }
        public virtual DbSet<VWCUT_ASTM_EN> VWCUT_ASTM_EN { get; set; }
        public virtual DbSet<VWCUT_ASTM_RU> VWCUT_ASTM_RU { get; set; }
        public virtual DbSet<VWCUT_CHEM_EN> VWCUT_CHEM_EN { get; set; }
        public virtual DbSet<VWCUT_CHEM_RU> VWCUT_CHEM_RU { get; set; }
        public virtual DbSet<VWCUT_OTHER_EN> VWCUT_OTHER_EN { get; set; }
        public virtual DbSet<VWCUT_OTHER_RU> VWCUT_OTHER_RU { get; set; }
        public virtual DbSet<VWCUT_STD_EN> VWCUT_STD_EN { get; set; }
        public virtual DbSet<VWCUT_STD_RU> VWCUT_STD_RU { get; set; }
        public virtual DbSet<VWOIL_ASTM_EN> VWOIL_ASTM_EN { get; set; }
        public virtual DbSet<VWOIL_ASTM_RU> VWOIL_ASTM_RU { get; set; }
        public virtual DbSet<VWOIL_CHEM_EN> VWOIL_CHEM_EN { get; set; }
        public virtual DbSet<VWOIL_CHEM_RU> VWOIL_CHEM_RU { get; set; }
        public virtual DbSet<VWOIL_OTHER_EN> VWOIL_OTHER_EN { get; set; }
        public virtual DbSet<VWOIL_OTHER_RU> VWOIL_OTHER_RU { get; set; }
        public virtual DbSet<VWOIL_STD_EN> VWOIL_STD_EN { get; set; }
        public virtual DbSet<VWOIL_STD_RU> VWOIL_STD_RU { get; set; }
        public virtual DbSet<Zen_BASIC_PROPERTIES> Zen_BASIC_PROPERTIES { get; set; }
        public virtual DbSet<Zen_Etalon> Zen_Etalon { get; set; }
        public virtual DbSet<Zen_Etalon_Spisok> Zen_Etalon_Spisok { get; set; }
        public virtual DbSet<Zen_EtalonTab> Zen_EtalonTab { get; set; }
        public virtual DbSet<Zen_Fr> Zen_Fr { get; set; }
        public virtual DbSet<Zen_Fr1> Zen_Fr1 { get; set; }
        public virtual DbSet<Zen_Fr2> Zen_Fr2 { get; set; }
        public virtual DbSet<Zen_INDEX_Rasst> Zen_INDEX_Rasst { get; set; }
        public virtual DbSet<ZLIGHTS_DATA> ZLIGHTS_DATA { get; set; }
        public virtual DbSet<Газовый_конденсат> Газовый_конденсат { get; set; }
    }
}
