//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMarkEntities : DbContext
    {
        public dbMarkEntities()
            : base("name=dbMarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANLGX> ANLGX { get; set; }
        public virtual DbSet<ASSAY_ORG_DATA> ASSAY_ORG_DATA { get; set; }
        public virtual DbSet<COPY_PROPERTIES> COPY_PROPERTIES { get; set; }
        public virtual DbSet<CUT_URALS> CUT_URALS { get; set; }
        public virtual DbSet<FF> FF { get; set; }
        public virtual DbSet<GEOREG> GEOREG { get; set; }
        public virtual DbSet<LIBRARY> LIBRARY { get; set; }
        public virtual DbSet<PROPERTIES> PROPERTIES { get; set; }
        public virtual DbSet<RPMS_BLEND> RPMS_BLEND { get; set; }
        public virtual DbSet<RPMS_CONV> RPMS_CONV { get; set; }
        public virtual DbSet<RPMS_RAWM> RPMS_RAWM { get; set; }
        public virtual DbSet<RPMS_RECURSE> RPMS_RECURSE { get; set; }
        public virtual DbSet<RPMS_RPMSFN> RPMS_RPMSFN { get; set; }
        public virtual DbSet<RPMS_SALES> RPMS_SALES { get; set; }
        public virtual DbSet<RPMS_SPEC> RPMS_SPEC { get; set; }
        public virtual DbSet<RPMS_SPECTEXT> RPMS_SPECTEXT { get; set; }
        public virtual DbSet<RPMS_UBAL> RPMS_UBAL { get; set; }
        public virtual DbSet<RPMS_YY1> RPMS_YY1 { get; set; }
        public virtual DbSet<URALS> URALS { get; set; }
        public virtual DbSet<VALUEPARAM> VALUEPARAM { get; set; }
        public virtual DbSet<Zen_Fr> Zen_Fr { get; set; }
        public virtual DbSet<Zen_Fr1> Zen_Fr1 { get; set; }
        public virtual DbSet<ZLIGHTS_DATA> ZLIGHTS_DATA { get; set; }
    }
}
