//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTIES
    {
        public int PROP_ID { get; set; }
        public string TTL { get; set; }
        public string TTL_SHORT { get; set; }
        public string XMLNODE { get; set; }
        public string UOM { get; set; }
        public Nullable<double> MIN { get; set; }
        public Nullable<double> MAX { get; set; }
        public Nullable<int> ASSAY_ID { get; set; }
        public Nullable<int> ASSAY_UOM { get; set; }
        public string INFO { get; set; }
        public Nullable<double> XVALUE { get; set; }
        public Nullable<double> CVALUE { get; set; }
        public bool ccFlag { get; set; }
        public bool fcFlag { get; set; }
        public bool stCrude { get; set; }
        public bool stFract { get; set; }
        public bool chemm { get; set; }
        public bool bpoints { get; set; }
        public bool other { get; set; }
        public Nullable<int> EXT_ID { get; set; }
        public Nullable<short> VSTDC { get; set; }
        public Nullable<short> VCHEMC { get; set; }
        public Nullable<short> VASTMC { get; set; }
        public Nullable<short> VSTDF { get; set; }
        public Nullable<short> VCHEMF { get; set; }
        public Nullable<short> VASTMF { get; set; }
        public Nullable<short> SEQALL { get; set; }
        public Nullable<short> SEQXLS { get; set; }
    }
}
