//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPMS_SPECTEXT
    {
        public int NNN { get; set; }
        public string POK1 { get; set; }
        public string POK2 { get; set; }
        public Nullable<double> WGT { get; set; }
        public Nullable<double> SUPPRESS { get; set; }
    }
}
