//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPMS_RPMSFN
    {
        public int NNN { get; set; }
        public string POK1 { get; set; }
        public string POK2 { get; set; }
        public Nullable<short> ID { get; set; }
        public Nullable<short> SPEC { get; set; }
        public Nullable<short> BLEND { get; set; }
        public Nullable<short> INSP { get; set; }
        public Nullable<short> ASSAY { get; set; }
        public Nullable<short> CRDQUAL { get; set; }
    }
}
