//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPMS_RECURSE
    {
        public int NNN { get; set; }
        public string POK1 { get; set; }
        public string POK2 { get; set; }
        public Nullable<double> TOL { get; set; }
        public Nullable<double> PERCENT { get; set; }
        public Nullable<double> INPUT { get; set; }
        public Nullable<double> OUTPUT { get; set; }
        public Nullable<double> TRACK { get; set; }
        public Nullable<double> CALCL { get; set; }
        public Nullable<double> STREAMS { get; set; }
        public Nullable<double> DEPATTR { get; set; }
        public Nullable<double> CONTROL { get; set; }
        public Nullable<double> SSS { get; set; }
    }
}
