//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPMS_CONV
    {
        public int XXX { get; set; }
        public string Neft { get; set; }
        public Nullable<double> SPG { get; set; }
        public Nullable<double> SUL { get; set; }
        public Nullable<double> C350 { get; set; }
        public Nullable<double> PAR { get; set; }
        public Nullable<double> CST { get; set; }
        public Nullable<double> SP2 { get; set; }
        public Nullable<double> SU2 { get; set; }
        public Nullable<double> C352 { get; set; }
        public Nullable<double> pa2 { get; set; }
        public Nullable<double> CS2 { get; set; }
    }
}
