//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class SULF_VS_AVBP
    {
        public int CUT_ID { get; set; }
        public string TTL { get; set; }
        public Nullable<double> SULF { get; set; }
        public Nullable<double> AVBP { get; set; }
    }
}
