//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNIINP_PROPERTIES
    {
        public Nullable<int> NEFT_ID { get; set; }
        public string NEFT_TTL { get; set; }
        public string COUNTRY { get; set; }
        public int CUT_ID { get; set; }
        public string CUT_TTL { get; set; }
        public Nullable<double> YLD { get; set; }
        public Nullable<double> NK { get; set; }
        public Nullable<double> KK { get; set; }
        public Nullable<double> SPG { get; set; }
        public Nullable<double> SULF { get; set; }
        public Nullable<double> ALCX { get; set; }
        public Nullable<double> NPHX { get; set; }
        public Nullable<double> AROX { get; set; }
        public Nullable<double> T50D86 { get; set; }
        public Nullable<double> FLASH_POINT { get; set; }
        public Nullable<double> POUR_POINT { get; set; }
        public Nullable<double> KV20 { get; set; }
        public Nullable<double> KV50 { get; set; }
        public Nullable<double> KV80 { get; set; }
        public Nullable<double> CETANE_NUM { get; set; }
        public Nullable<double> CCOX { get; set; }
    }
}
