//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zen_Etalon_Spisok
    {
        public string IDnef { get; set; }
        public string Название { get; set; }
        public string Сера { get; set; }
        public string V350 { get; set; }
        public string Параф { get; set; }
        public string Плотн { get; set; }
        public string Вязк { get; set; }
        public string Расст { get; set; }
        public string Индекс { get; set; }
        public string Рецепт { get; set; }
    }
}
