//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zen_Fr1
    {
        public int CUT_ID { get; set; }
        public Nullable<int> NEFT_ID { get; set; }
        public string TTL { get; set; }
        public bool VOL { get; set; }
        public Nullable<double> YLD { get; set; }
        public bool KND { get; set; }
    }
}
