//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zen_INDEX_Rasst
    {
        public int NEFT_ID { get; set; }
        public string TTL { get; set; }
        public Nullable<double> SPG { get; set; }
        public Nullable<double> SUL { get; set; }
        public Nullable<double> Vih350 { get; set; }
        public Nullable<double> PAR { get; set; }
        public Nullable<double> CST { get; set; }
        public Nullable<double> Rasst { get; set; }
        public Nullable<int> Ind { get; set; }
    }
}
