//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZLIGHTS_DATA
    {
        public string CUT_NAME { get; set; }
        public Nullable<int> CUT_ID { get; set; }
        public Nullable<double> Y_BENZ { get; set; }
        public Nullable<double> Y_KERO { get; set; }
        public Nullable<double> Y_DSS { get; set; }
        public Nullable<double> Y_DSW { get; set; }
        public bool ASSF { get; set; }
        public Nullable<double> SOLUTION { get; set; }
    }
}
