//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkOil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Газовый_конденсат
    {
        public string CUT { get; set; }
        public Nullable<double> C276 { get; set; }
        public Nullable<double> C282 { get; set; }
        public Nullable<double> FR { get; set; }
        public Nullable<double> SUM { get; set; }
        public Nullable<double> C239 { get; set; }
        public Nullable<double> C254 { get; set; }
        public Nullable<double> C270 { get; set; }
        public Nullable<double> C271 { get; set; }
        public Nullable<double> C272 { get; set; }
        public Nullable<double> N2A { get; set; }
        public Nullable<double> C378 { get; set; }
        public Nullable<double> C336 { get; set; }
        public Nullable<double> C266 { get; set; }
        public Nullable<double> C265 { get; set; }
        public Nullable<double> C245 { get; set; }
        public Nullable<double> C248 { get; set; }
        public Nullable<double> C361 { get; set; }
        public Nullable<double> C263 { get; set; }
        public Nullable<double> C307 { get; set; }
        public Nullable<double> C279 { get; set; }
    }
}
